name: elegal
description: Escritorio Legal para web

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  webview_flutter: ^1.0.0
  js: ^0.6.2

  firebase_auth_web: ^3.3.17
  cloud_firestore_web: ^2.6.17
  flutter_firebase_chat_core: 1.5.1
  shared_preferences: ^2.0.15

  firebase_core: ^1.9.0
  cloud_firestore: ^3.0.4
  cloud_functions: 3.0.4
  google_sign_in: ^5.2.0
  firebase_auth: ^3.1.4

  flutter_chat_ui: ^1.5.3
  photo_view: ^0.13.0
  flutter_chat_types: 3.4.3
  record: ^3.0.2
  just_audio: ^0.9.18
  firebase_storage: ^10.2.5

  firebase_storage_web: ^3.2.19
  carousel_slider: ^4.0.0

  path_provider: ^2.0.8
  open_file: ^3.2.1
  file_picker: ^4.2.7
  mime: ^1.0.1
  image_picker_web: ^2.1.1
  onesignal_flutter: ^3.0.0
  http: ^0.13.4
  find_dropdown: ^1.0.0

  cross_file: ^0.3.3+1
  image_picker: ^0.8.5+3
  url_launcher: ^6.1.5

  rflutter_alert: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/audio/
    - assets/img/
