name: e_legal
description: Escritorio legal

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #firebase_core: ^1.10.6
  firebase_core: ^2.3.0 #^1.10.6
  google_sign_in: ^5.2.0
  #firebase_auth: ^3.3.19
  firebase_auth: ^4.1.3
  #cloud_firestore: ^3.1.17
  cloud_firestore: ^4.1.0
  flutter_launcher_icons: ^0.9.2
  cupertino_icons: ^1.0.2
  country_pickers: ^2.0.0
  http: ^0.13.4
  flutter_stripe: ^3.0.2
  #firebase_storage: ^10.2.17
  firebase_storage: ^11.0.6
  #flutter_firebase_chat_core: 1.5.1
  flutter_firebase_chat_core: ^1.6.4
  record: ^3.0.2
  just_audio: ^0.9.18
  #flutter_chat_types: 3.2.1
  flutter_chat_types: ^3.6.0
  photo_view: ^0.13.0
  faker: ^2.0.0
  file_picker: ^4.2.7
  flutter_chat_ui: ^1.5.3
  image_picker: ^0.8.4+4
  mime: ^1.0.1
  open_file: ^3.2.1
  path_provider: ^2.0.8
  carousel_slider: ^4.0.0
  rflutter_alert: ^2.0.4
  find_dropdown: ^1.0.0
  awesome_notifications: ^0.6.21
  flutter_facebook_auth: ^4.3.4+2
  onesignal_flutter: ^3.5.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.5

  sn_progress_dialog: ^1.0.8
  sign_in_with_apple: ^4.2.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/img/
