name: flutter_chat
description: Social Chat for Flutter android and iOS using firebase as backend services.

version: 1.1.0
homepage: https://github.com/ankesh-kumar/Flutter-chat-sdk
environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  firebase_core: ^1.0.1
  firebase_auth: ^1.0.1
  firebase_analytics: ^7.1.1
  firebase_storage: ^8.0.0
  firebase_messaging: ^9.0.0
  firebase_database: ^6.1.0
  cloud_firestore: ^1.0.1
  fluttertoast: ^7.1.1
  image_picker: ^0.6.2+3
  photo_view: ^0.10.2
  google_sign_in: ^4.0.4
  flutter_native_image: ^0.0.4
  cached_network_image: ^2.0.0-rc
  #flutter_dialogflow: ^0.1.3
  intl: ^0.17.0
  carousel_slider: ^2.3.1
  shared_preferences: ^2.0.5
  path_provider: ^2.0.1
  #flutter_sound: ^8.0.1+11
  flutter_sound: 8.1.1
  permission_handler: ^6.1.1
  file_picker: ^3.0.0
  flutter_downloader: ^1.6.0-nullsafety.0
  open_file: ^3.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/

